# Generated by Django 3.2.18 on 2023-03-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingapp', '0002_auto_20230301_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpattern',
            name='file',
            field=models.FileField(default='documents/document.pdf', upload_to='documents'),
        ),
    ]
