# Generated by Django 3.2.18 on 2023-03-01 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sewingapp', '0003_postpattern_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpattern',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
