# Generated by Django 3.2.18 on 2023-03-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingapp', '0004_alter_postpattern_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpattern',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
