# Generated by Django 3.2.18 on 2023-03-03 17:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sewingapp', '0005_alter_postpattern_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpattern',
            name='featured_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postpattern',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postpattern',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdf'),
        ),
    ]
