# Generated by Django 3.2.18 on 2023-03-05 16:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sewingapp', '0007_postpattern_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpattern',
            name='suggested_fabrics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('stretch', 'Stretch'), ('non_stretch', 'Non-stretch'), ('wool', 'Wool'), ('denim', 'Denim'), ('silk', 'Silk'), ('cotton', 'Cotton'), ('lace', 'Lace'), ('canvas', 'Canvas'), ('chiffon', 'Chiffon'), ('jersey', 'Jersey'), ('gingham', 'Gingham'), ('spandex', 'Spandex'), ('organza', 'Organza'), ('none', 'None')], default='none', max_length=98),
        ),
    ]
