# Generated by Django 3.2.18 on 2023-03-06 16:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sewingapp', '0008_postpattern_suggested_fabrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpattern',
            name='suggested_fabrics',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('stretch', 'Stretch'), ('non_stretch', 'Non-stretch'), ('wool', 'Wool'), ('denim', 'Denim'), ('silk', 'Silk'), ('cotton', 'Cotton'), ('lace', 'Lace'), ('canvas', 'Canvas'), ('chiffon', 'Chiffon'), ('jersey', 'Jersey'), ('gingham', 'Gingham'), ('spandex', 'Spandex'), ('organza', 'Organza')], max_length=93, null=True),
        ),
    ]
