# Generated by Django 3.2.18 on 2023-03-06 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sewingapp', '0009_alter_postpattern_suggested_fabrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpattern',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='pattern_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
